### ISSUE TITLE
How to build it for android ?

### ISSUE THREAD

**Issue by carl1234a** [FreeSlave/hlsdk-xash3d#1]
I have problem about built it for android first 
I write in terminal ndk-build but not working
And i use xash project waf but it's say
OSError: [Errno 2] no such file or directory 'sdk-tools,/build-tools'
How to fix it ? plz plz i wait 5 mouth for waiting to answer it

**Comment by FreeSlave** [comment]
Hello. I don't make Android builds. You better ask at the original repository https://github.com/FWGS/hlsdk-xash3d
