### ISSUE TITLE
inability to have new NPC's

### ISSUE THREAD

**Issue by WalidDreemurr** [FreeSlave/hlsdk-xash3d#12]
i've been trying out those new NPC's you added in the mod, specifically "monster_floater", "monster_flybee", and "monster_panthereye", just so i can test them out myself and see if they work as i expected them to from the video i saw about how they're meant to behave. but somehow, even those two flying NPC's in the "flyers_demo.bsp" map, they don't seem to appear at all. i have the models necessary for them like you recommended us to do, but i wonder to myself if this is either a bug specifically for me or a mistake you made that needs a double-check. whatever the reason is, i hope it can be sorted out

**Comment by FreeSlave** [comment]
Hi. These monsters are not enabled by default.
Read about feature configuration https://github.com/FreeSlave/halflife-featureful/wiki/Feature-configuration

Maybe I should enable for the sample mod though.

**Comment by WalidDreemurr** [comment]
oh yeah right, i forgot that the "featureful_monsters.cfg" exists, my bad. and also thank you for helping out with this small issue, i wouldn't have easily figured out the solution for the issue if it wasn't for you ✨
