### ISSUE TITLE
missing "env_blowercannon" in JACK

### ISSUE THREAD

**Issue by WalidDreemurr** [FreeSlave/hlsdk-xash3d#13]
hi, i'm sorry if the issue is not that relevant to the mod you made for us, but i don't think i can see the "env_blowercannon" entity in the list of my Object Properties. i've checked the FGD, and it does have it, but maybe there's something about it that i'm missing in the FGD or something.

do you perhaps know what's the solution of this issue by any chance?

**Comment by FreeSlave** [comment]
What version of JACK do you use?
Make sure you're using the right game profile when loading a map (i.e. the profile that uses halflife_featureful.fgd)
There're some `env_blowecannon` entities on featureful_demo map. The map source is available in the sample mod. Does it show the descriptive properties if you go into the entity properties?

**Comment by WalidDreemurr** [comment]
i'm using J.A.C.K. 1.1.3773, aka the free version of Jackhammer Editor. also i did open the featureful_demo map file with J.A.C.K, but even though that it doesn't show in the list.

and i've been using the pirated version of half-life, specifically the version where you can see the Menu look like how we'd see it on Steam while putting it on Beta version in the properties

**Comment by FreeSlave** [comment]
Does it show other new entities in the list? E.g. `env_dlight`.

**Comment by WalidDreemurr** [comment]
yes, actually. those extra entities you made like `env_rope`, `env_snow`, and `env_dlight` of course. but i guess `env_blowercannon` is the only exception to not make it to J.A.C.K, unfortunately

**Comment by FreeSlave** [comment]
When you load the map with the configuration made for Featureful SDK for the first time after you boot the editor, does it show any errors in the Messages field (Window -> Messages)? Besides missing models.

**Comment by WalidDreemurr** [comment]
actually, now that you mentioned it, i opened up JACK and it mentioned that i can download the latest version. and once i did so, i think the problem was solved after i found out that i wasn't actually using the latest version of JACK. apparently i was using version 1.1.1064, and i guess it's either because of the version of JACK that didn't seem to get along with the entity, or maybe because of a certain setting that i did was wrong. so i apologize if i have been wasting your time over this slight issue, hopefully things are okay between us now and i hope you'll continue on updating the mod for as long as you wish for.
