### ISSUE TITLE
multi_manager doesn't recognize `#on` and `#off` states

### ISSUE THREAD

**Issue by mfaizsyahmi** [FreeSlave/hlsdk-xash3d#9]
As per [documentation](https://github.com/FreeSlave/halflife-featureful/wiki/Other-entities#multi_manager), `multi_manager` is said to support all of `#0`, `#1`, `#off`, and `#on` to set the trigger state of the targets. 

In my case, I want to use exclusively `#on` and `#off`, and avoid `#0` and `#1` to not be ambiguous with normal vanilla usage. 

But the `multi_manager` doesn't recognize these values, and just send a trigger state as usual.

Attached is a demonstration map of the issue.
[featureful_mm_test.zip](https://github.com/user-attachments/files/16261072/featureful_mm_test.zip)

entity excerpt:
```
{
"classname" "multi_manager"
"targetname" "test_mm"
"sprite1#off" "0"
"sprite2#on" "0"
"origin" "64 0 24"
}
```
console excerpt:
```
Firing: (test_mm)
Found: multi_manager, firing (test_mm, USE_TOGGLE, called by 'func_button', activated by 'player')
Firing: (sprite2)
Found: env_sprite, firing (sprite2, USE_TOGGLE, called by 'multi_manager', activated by 'player')
Firing: (sprite1)
Found: env_sprite, firing (sprite1, USE_TOGGLE, called by 'multi_manager', activated by 'player')
```

**Comment by mfaizsyahmi** [comment]
oh whoops, the suffix is supposed to be in the VALUE, huh. my bad.

**Comment by FreeSlave** [comment]
It's supposed to be in delay value, like it's made in Sven Co-op, yep.
Putting the suffix in the target name would mess with editor recognition of the entity connections (not relevant for `multi_manager` though as it relies on keys, but it's relevant for Featureful-specific `multi_trigger` which is equivavelnt to `multi_manager` with a different interface).
